[package]
name = "satway_build_info"
version = "0.1.4"
edition = "2021"
authors = ["zhangjianshe <zhangjianshe@gmail.com>"]
license = "MIT OR Apache-2.0"
publish = true
description = "provide a build information extract for build.rs script"
homepage = "https://github.com/zhangjianshe/satway-build-info.git"
keywords = ["build","git","build-info"]
[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
